name: Molas Spa
favicon: null
layout_spectrum: 0.89160504960455
typography_spectrum: 0.3367013137321919
title: Molas Spa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7757313931360841
  lightness: 0.9408905529417098
  saturation: 0.052675731712952256
  rhythmicContrast: 0.7622854048386216
purpose: []
